### ISSUE TITLE
undefined local variable or method `secondary_regex' for #<MangaSync:0x1696188> (NameError)

### ISSUE THREAD

**Issue by wilfriedroset** [vidyuthd/mangasync#7]
I'm currently unable to download any manga due to a NameError. I've tried several manga and/or source

```
# ruby manga_sync.rb
manga_sync.rb:105: warning: else without rescue is useless
input series name : toriko
input start chapter no : 334
input end chapter no(if you need only one chapter, the leave this blank by pressing enter or give same
    value as start chapter) : 334
input manga source by number (this can either of be mangapanda,mangareader,mangafox,mangajoy,mangasee,mangatown,readmanga,mangafreak,mangahere,mangahit -leave this blank
    if you are not sure by pressing enter button): mangahit
"http://www.mangahit.com/toriko/334/1"
"hitting url:  http://www.mangahit.com/toriko/334/1"
manga_sync.rb:58:in `block (2 levels) in method': undefined local variable or method `secondary_regex' for #<MangaSync:0x1696188> (NameError)
        from manga_sync.rb:57:in `block in method'
        from /usr/lib/ruby/1.9.1/open-uri.rb:150:in `open_uri'
        from /usr/lib/ruby/1.9.1/open-uri.rb:677:in `open'
        from /usr/lib/ruby/1.9.1/open-uri.rb:33:in `open'
        from manga_sync.rb:53:in `method'
        from manga_sync.rb:77:in `block in getThread'
# ruby --version
ruby 1.9.3p194 (2012-04-20 revision 35410) [arm-linux-eabihf]
# git log -1
commit cbab675b762424725ed61c9b125ffac49c6c5738
Author: vidyuthd <vidyuth.bitsgoa@gmail.com>
Date:   Fri Jul 3 22:25:28 2015 +0530

    1.Adding  source mangahit.com
    2. adding a prompt for creating dir(series & chapter)
```

**Comment by vidyuthd** [comment]
Sorry for lateness, 

this is now fixed, this was causing by unnecessary deletion of statement. I have verified that it works with given input provided by you.

Thanks for raising
